# -*- encoding: utf-8 -*-
{
    'name': 'Theme Laze',
    'category': 'Theme/eCommerce',
    'sequence': 1000,
    'version': '1.2',
    'license': 'OPL-1',
    'author': 'Atharva System',
    'support': 'support@atharvasystem.com',
    'website' : 'https://www.atharvasystem.com',
    'live_test_url': 'https://laze-v15.atharvasystem.com',
    'description': """Theme Laze is one of the most powerful, amazing and flexible theme on Odoo store.""",
    'depends': ['atharva_theme_base'],
    'data': [
        'views/headers/headers.xml',
        'views/headers/switch.xml',
        'views/footers/footers.xml',
        'views/footers/switch.xml',
        'views/megamenu.xml',
        'views/product_rating.xml',
        'views/product_label.xml',
        'views/similar_product.xml',
        'views/quick_add_to_cart.xml',
        'views/quick_view.xml',
        'views/shop_layout.xml',
        'views/product_brand.xml',
        'views/product_details.xml',
        'views/product_tags.xml',
        'views/menu_tag.xml',
        'views/shop.xml',
        'views/login_popup.xml',
        'views/laze_button.xml',
        'views/snippets/s_laze_snippet_builder.xml',
        'views/snippets/s_brand_slider.xml',
        'views/snippets/s_category_slider.xml',
        'views/snippets/s_category_product_slider.xml',
        'views/snippets/s_product_slider.xml',
        'views/snippets/s_best_seller_product.xml',
        'views/snippets/s_product_offer_slider.xml',
        'views/snippets/s_category_grid_snippet.xml',
        'views/snippets/s_blog_slider.xml',
        'views/snippets/slider_and_grid/brand_slider_grid_layout.xml',
        'views/snippets/slider_and_grid/category_slider_grid_layout.xml',
        'views/snippets/slider_and_grid/product_slider_grid_layout.xml',
        'views/snippets/slider_and_grid/best_seller_product_slider_grid_layout.xml',
        'views/snippets/slider_and_grid/category_grid_layout.xml',
        'views/snippets/slider_and_grid/blog_slider_grid_layout.xml',
        'views/snippets/slider_and_grid/product_offer_slider_layout.xml',
        'views/snippets/slider_and_grid/snippet_base_templates.xml',
        'views/snippets/s_image_hotspot.xml',
        'views/snippets/s_offer_banner.xml',
        'views/quick_load_product.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            "theme_laze/static/src/scss/variables.scss",
            "theme_laze/static/src/scss/shop/shop-1.scss",
            "theme_laze/static/src/scss/headers/*.scss",
            "theme_laze/static/src/scss/footers/*.scss",
            "theme_laze/static/src/scss/buttons.scss",
            "theme_laze/static/src/js/frontend/megamenu.js",

            "theme_laze/static/src/js/snippets/**/*.scss",
            "theme_laze/static/src/js/snippets/**/000.js",

            'theme_laze/static/src/scss/base.scss',
            'theme_laze/static/src/scss/shop.scss',
            'theme_laze/static/src/scss/modal.scss',
            'theme_laze/static/src/scss/product-detail.scss',
            'theme_laze/static/src/scss/mega-menu.scss',
            'theme_laze/static/src/scss/brand.scss',
            'theme_laze/static/src/scss/product-snippet.scss',
            'theme_laze/static/src/scss/blog-snippet.scss',
            'theme_laze/static/src/scss/category-snippet.scss',
            'theme_laze/static/src/scss/hotspot.scss',
            'theme_laze/static/src/scss/shop/full-layout.scss',
            'theme_laze/static/src/scss/headers/common_header.scss',
            'theme_laze/static/src/scss/footers/common_footer.scss',
            'theme_laze/static/src/js/base/quickProdView.js',
            'theme_laze/static/src/js/frontend/similarProduct.js',
            'theme_laze/static/src/js/frontend/quickAddToCart.js',
            'theme_laze/static/src/js/frontend/quickView.js',
            'theme_laze/static/src/js/frontend/shopCore.js',
            'theme_laze/static/src/js/frontend/productCore.js',
            'theme_laze/static/src/js/base/miniCartDialog.js',
            'theme_laze/static/src/js/frontend/miniCart.js',
            'theme_laze/static/src/js/frontend/login.js',
            'theme_laze/static/src/js/frontend/quickLoadProd.js',
        ],
        'web._assets_primary_variables': [
            'theme_laze/static/src/scss/assets_primary_variables/laze_primary_variables.scss'
        ],
        'web._assets_frontend_helpers': [
            'theme_laze/static/src/scss/assets_frontend_helpers/laze_frontend_helpers.scss',
        ],
        'web.assets_common': [
            'theme_laze/static/src/js/base/coreMixins.js',
        ],
        'website.assets_editor':[
            'theme_laze/static/src/scss/editor_popup.scss',
            'theme_laze/static/src/js/base/megaDialog.js',
            'theme_laze/static/src/js/base/recordSelector.js',
            'theme_laze/static/src/js/editor/options.js',
            'theme_laze/static/src/js/base/brandCatDialog.js',
            'theme_laze/static/src/js/base/productDialog.js',
            'theme_laze/static/src/js/base/offerDialog.js',
            'theme_laze/static/src/js/base/catProductDialog.js',
            'theme_laze/static/src/js/base/catGridDialog.js',
            'theme_laze/static/src/js/snippets/**/options.js',

        ],
        'web.assets_qweb': [
            'theme_laze/static/src/xml/snippets/base_templates.xml',
            'theme_laze/static/src/xml/snippets/cat_brand_dialog.xml',
            'theme_laze/static/src/xml/snippets/category_grid_dialog.xml',
            'theme_laze/static/src/xml/snippets/offer_slider_dialog.xml',
            'theme_laze/static/src/xml/snippets/product_dialog.xml',
            'theme_laze/static/src/xml/snippets/product_offer_dialog.xml',
        ],
    },
    'snippet_lists': {
        'homepage': ['s_cover', 's_text_image', 's_image_text', 's_masonry_block', 's_call_to_action', 's_picture'],
        'about_us': ['s_text_image', 's_image_text', 's_title', 's_company_team'],
        'our_services': ['s_three_columns', 's_quotes_carousel', 's_references'],
        'pricing': ['s_comparisons'],
    },
    'price': 195.00,
    'currency': 'EUR',
    'images': ['static/description/laze_description.png','static/description/laze_screenshot.gif'],
    'application': False,
    'auto_install': False,
}
